stages:
  - deploy

image: node:latest

variables:
  HUGO_VERSION: 0.101.0 # will get Extended Version Below
  DART_SASS_VERSION: 1.53.0
  BEARER_TOKEN: $BEARER_TOKEN
  TOKEN: $TOKEN
  TOKEN_SECRET: $TOKEN_SECRET
  CONSUMER_KEY: $CONSUMER_KEY
  CONSUMER_SECRET: $CONSUMER_SECRET
  GIT_DEPTH: 0
  # WEBMENTION_IO_TOKEN: $WEBMENTION_IO_TOKEN

deploySite:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # above line only if using cron jobs
  environment:
    name: production
    url: https://hugo-site-vercel.vercel.app
  script:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${DART_SASS_VERSION}/sass_embedded-${DART_SASS_VERSION}-linux-x64.tar.gz
    - tar -xvf sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
    - sass_embedded/dart-sass-embedded --version
    - hugo --gc --minify
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
